# Use the locally built base image
FROM base:local AS base

# Set the working directory
WORKDIR /opt

# Clone vcpkg repository
RUN git clone --depth 1 https://github.com/Microsoft/vcpkg.git \
    && /opt/vcpkg/bootstrap-vcpkg.sh -disableMetrics

# Install vcpkg dependencies
RUN /opt/vcpkg/vcpkg install vcpkg-cmake POCO

# Set the working directory for the main build
WORKDIR /app

# Copy the project files to the working directory
COPY . .

# Build the project
RUN cmake -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake .

# Use the locally built vcpkg image
FROM vcpkg:local AS vcpkg

# Continue with the rest of your Dockerfile...
