FROM ubuntu:22.04

# Install necessary dependencies
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        gdb \
        git \
        libdbus-1-3 \
        libgbm1 \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libglib2.0-dev \
        libssl-dev \
        libx11-xcb1 \
        libxcb-image0 \
        libxcb-keysyms1 \
        libxcb-randr0 \
        libxcb-shape0 \
        libxcb-shm0 \
        libxcb-xfixes0 \
        libxcb-xtest0 \
        libxfixes3 \
        pkgconf \
        tar \
        unzip \
        zip

# Install ALSA
RUN apt-get install -y libasound2 libasound2-plugins alsa alsa-utils alsa-oss

# Install Pulseaudio
RUN apt-get install -y pulseaudio pulseaudio-utils

# Install Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# Set the entry point
ENTRYPOINT ["/bin/bash"]
